-- LMS Schema for Cloudflare D1

INSERT OR IGNORE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, group_name, sort_order, created_at, updated_at) VALUES ('01M4E3NQDSV36ARRFVFDXJP9CA', 'course_categories', 'Course Categories', 'Category', 'folder', '["drafts"]', 'LMS', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR IGNORE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, group_name, sort_order, created_at, updated_at) VALUES ('01M4E3NQE7T2KYMMPXNVEZBA9Z', 'courses', 'Courses', 'Course', 'book-open', '["drafts","revisions","search","seo"]', 'LMS', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR IGNORE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, group_name, sort_order, created_at, updated_at) VALUES ('01M4E3NQEVYPVW6YHPF4Y33WJH', 'lessons', 'Lessons', 'Lesson', 'play-circle', '["drafts","revisions","search","seo"]', 'LMS', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR IGNORE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, group_name, sort_order, created_at, updated_at) VALUES ('01M4E3NQCD2BNKAG2DZJGMEJ59', 'membership_plans', 'Membership Plans', 'Plan', 'credit-card', '["drafts"]', 'LMS', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR IGNORE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, group_name, sort_order, created_at, updated_at) VALUES ('01M4E3NQEMREFNJJFWXX7B69Y9', 'modules', 'Modules', 'Module', 'folder', '["drafts"]', 'LMS', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCE56HGFZHF5B34EYPS', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'name', 'Plan Name', 'string', 1, '', 0, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCEYHCZEG68X8HC3X34', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'description', 'Description', 'text', 0, '', 1, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCEH244HQN47KG7S2HP', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'price', 'Price', 'number', 1, '{"min":0}', 2, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCETWQQCTHY6HPEQ2KG', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'currency', 'Currency', 'string', 0, '', 3, '"USD"', NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCEX3B2NDEJ5R29R257', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'sale_price', 'Sale Price', 'number', 0, '{"min":0}', 4, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCE4HNMCMZD99DRBPRD', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'sale_start', 'Sale Start', 'datetime', 0, '', 5, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCE4DPXQGAK311YG4FA', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'sale_end', 'Sale End', 'datetime', 0, '', 6, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCEG417P1JX5DF0VRA2', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'billing_period', 'Billing Period', 'string', 0, '{"choices":["monthly","quarterly","yearly","lifetime"]}', 7, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCEYM8PB0E963WM614N', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'features', 'Features', 'json', 0, '', 8, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCEN5CARKQBNCTX3GEF', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'limits', 'Limits', 'json', 0, '', 9, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQCE7ABN9E8K4C7P72FM', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'sort_order', 'Sort Order', 'integer', 0, '', 10, '0', NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQDSEY0T2BB7XQ0Q69MD', '01M4E3NQDSV36ARRFVFDXJP9CA', 'name', 'Name', 'string', 1, '', 0, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQDS72HTS81238MX6FCP', '01M4E3NQDSV36ARRFVFDXJP9CA', 'description', 'Description', 'text', 0, '', 1, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQDSZFYFEJCDCNP3H263', '01M4E3NQDSV36ARRFVFDXJP9CA', 'sort_order', 'Sort Order', 'integer', 0, '', 2, '0', NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE7E597W6HGXT77C302', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'title', 'Title', 'string', 1, '', 0, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE77CEMVAYR00PEKNK9', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'excerpt', 'Excerpt', 'text', 0, '', 1, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE7TXP6CEX49VJ8ZPMS', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'description', 'Description', 'text', 0, '', 2, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE7MF8968FTFNNHH6HW', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'featured_image', 'Featured Image', 'image', 0, '', 3, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE753PHANRPDGBM2JP6', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'content', 'Content', 'portableText', 0, '', 4, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE7SA0R7T79M0FFJ91Z', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'category_id', 'Category', 'reference', 0, '{"collection":"course_categories"}', 5, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE7YWCNRJSRPA920HHZ', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'prerequisite_id', 'Prerequisite Course', 'reference', 0, '{"collection":"courses"}', 6, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE7EG2P4ZZP5QNEQGQ8', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'access_level', 'Access Level', 'string', 0, '{"choices":["free","membership","purchase"]}', 7, '"membership"', NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE8QKKX0DSCSRZAR7ZN', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'is_purchasable', 'Individual Purchase', 'boolean', 0, '', 8, 'false', NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE8SVGVVTFD7WXNVM8V', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'required_plan_ids', 'Required Plans', 'json', 0, '', 9, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE869F3HHYQ1CA6EKKK', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'price', 'Price', 'number', 0, '{"min":0}', 10, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE8A0M250YAJY906YJ7', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'currency', 'Currency', 'string', 0, '', 11, '"USD"', NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE8C58W8Y9V007YYDM8', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'sale_price', 'Sale Price', 'number', 0, '{"min":0}', 12, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE8P5F2JE2HD22TAN56', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'sale_start', 'Sale Start', 'datetime', 0, '', 13, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE8QAAT8VDH9XFF9Y8N', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'sale_end', 'Sale End', 'datetime', 0, '', 14, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE86J0XFHNF5CGDP1ZY', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'duration_hours', 'Duration (hours)', 'number', 0, '', 15, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE8S20ZB0HXCP1YNYMX', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'difficulty', 'Difficulty', 'string', 0, '{"choices":["beginner","intermediate","advanced"]}', 16, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQE90E90WA0A3HQ1GZ2J', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'featured', 'Featured', 'boolean', 0, '', 17, 'false', NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEM69BGZK6ZSPCDR1Z7', '01M4E3NQEMREFNJJFWXX7B69Y9', 'title', 'Title', 'string', 1, '', 0, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEMJENE970B3DBQ85BX', '01M4E3NQEMREFNJJFWXX7B69Y9', 'course_id', 'Course', 'reference', 1, '{"collection":"courses"}', 1, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEMME2S48K910CR7GVP', '01M4E3NQEMREFNJJFWXX7B69Y9', 'description', 'Description', 'text', 0, '', 2, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEMBDAH3QT2DQB7PYQ3', '01M4E3NQEMREFNJJFWXX7B69Y9', 'sort_order', 'Sort Order', 'integer', 0, '', 3, '0', NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEVHYHNH2GXJFH27RTC', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'title', 'Title', 'string', 1, '', 0, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEV4N3837WQRT91434A', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'module_id', 'Module', 'reference', 1, '{"collection":"modules"}', 1, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEVTGRH79RM7XWESAFJ', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'course_id', 'Course', 'reference', 1, '{"collection":"courses"}', 2, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEV9031Z6Z6XHYZFGZ8', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'excerpt', 'Excerpt', 'text', 0, '', 3, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEVQDZBQ7YTTZD0V925', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'featured_image', 'Featured Image', 'image', 0, '', 4, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEWEM85B0FYWTPXJ9KN', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'content', 'Content', 'portableText', 0, '', 5, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEW4AZ6W6Z79EK1VZ8Q', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'summary', 'Summary', 'portableText', 0, '', 6, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEW8HKQMFTZTVFNPHN8', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'video_url', 'Video URL', 'string', 0, '', 7, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEWYBT02Q5P46FWZMXB', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'duration_minutes', 'Duration (minutes)', 'integer', 0, '', 8, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEWS021A4WH84WREDHQ', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'sort_order', 'Sort Order', 'integer', 0, '', 9, '0', NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEWS7J22M78XCHQF68J', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'is_preview', 'Free Preview', 'boolean', 0, '', 10, 'false', NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEW014GF4S9VE08MH67', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'prerequisite_id', 'Prerequisite Lesson', 'reference', 0, '{"collection":"lessons"}', 11, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEW392K257T9AHTBNXX', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'complexity', 'Complexity', 'string', 0, '{"choices":["easy","medium","hard"]}', 12, NULL, NULL, '2026-10-08 15:56:22', 'undefined');
INSERT OR IGNORE INTO _emdash_fields (id, collection_id, slug, label, type, required, options, sort_order, default_value, group_name, created_at, updated_at) VALUES ('01M4E3NQEWTM4E7CMGYDY1XZCC', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'resources', 'Resources', 'json', 0, '', 13, NULL, NULL, '2026-10-08 15:56:22', 'undefined');

-- Tables
CREATE TABLE "ec_posts" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "title" text default '' not null, "featured_image" text, "content" json, "excerpt" text, constraint "ec_posts_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_pages" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "title" text default '' not null, "content" json, constraint "ec_pages_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_membership_plans" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "name" text default '' not null, "description" text, "price" real default 0.0 not null, "currency" text, "sale_price" real, "sale_start" text, "sale_end" text, "billing_period" text, "features" json, "limits" json, "sort_order" integer, constraint "ec_membership_plans_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_course_categories" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "name" text default '' not null, "description" text, "sort_order" integer, constraint "ec_course_categories_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_courses" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "title" text default '' not null, "excerpt" text, "description" text, "featured_image" text, "content" json, "category_id" text, "prerequisite_id" text, "access_level" text, "is_purchasable" integer, "required_plan_ids" json, "price" real, "currency" text, "sale_price" real, "sale_start" text, "sale_end" text, "duration_hours" real, "difficulty" text, "featured" integer, constraint "ec_courses_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_modules" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "title" text default '' not null, "course_id" text default '' not null, "description" text, "sort_order" integer, constraint "ec_modules_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_lessons" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "title" text default '' not null, "module_id" text default '' not null, "course_id" text default '' not null, "excerpt" text, "featured_image" text, "content" json, "summary" json, "video_url" text, "duration_minutes" integer, "sort_order" integer, "is_preview" integer, "prerequisite_id" text, "complexity" text, "resources" json, constraint "ec_lessons_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_quizzes" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "title" text default '' not null, "lesson_id" text default '' not null, "description" text, "passmark" integer, "pass_required" integer, "timer_minutes" integer, "allow_reset" integer, "random_order" integer, "grade_type" text, constraint "ec_quizzes_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_questions" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "quiz_id" text default '' not null, "question" text default '' not null, "question_image" text, "type" text, "answers" json, "grade" real, "sort_order" integer, "explanation" text, "random_order" integer, constraint "ec_questions_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_coupons" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "code" text default '' not null, "description" text, "type" text, "value" real default 0.0 not null, "applies_to" text, "applicable_ids" json, "usage_limit" integer, "usage_count" integer, "per_user_limit" integer, "min_purchase" real, "valid_from" text, "valid_until" text, constraint "ec_coupons_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_course_reviews" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "course_id" text default '' not null, "user_id" text default '' not null, "rating" integer default 0 not null, "title" text, "content" text, "verified_purchase" integer, "helpful_count" integer, constraint "ec_course_reviews_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_certificate_templates" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "name" text default '' not null, "description" text, "design" text default '' not null, "course_id" text, constraint "ec_certificate_templates_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_memberships" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "plan_id" text default '' not null, "membership_type" text, "started_at" text, "expires_at" text, "cancelled_at" text, "payment_provider" text, "subscription_id" text, constraint "ec_memberships_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_orders" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "type" text default '' not null, "item_id" text default '' not null, "subtotal" real, "discount_amount" real, "amount" real default 0.0 not null, "currency" text, "coupon_id" text, "coupon_code" text, "payment_provider" text, "payment_id" text, "metadata" json, constraint "ec_orders_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_enrollments" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "course_id" text default '' not null, "source" text default '' not null, "order_id" text, "progress" integer, "started_at" text, "completed_at" text, constraint "ec_enrollments_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_lesson_progress" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "lesson_id" text default '' not null, "course_id" text default '' not null, "completed" integer, "completed_at" text, "last_position" integer, constraint "ec_lesson_progress_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_quiz_submissions" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "quiz_id" text default '' not null, "lesson_id" text, "course_id" text, "score" real default 0.0 not null, "max_score" real default 0.0 not null, "percentage" real, "passed" integer, "answers" json, "started_at" text, "submitted_at" text, "time_spent_seconds" integer, constraint "ec_quiz_submissions_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE "ec_certificates" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "course_id" text default '' not null, "template_id" text default '' not null, "certificate_number" text default '' not null, "issued_at" text, "metadata" json, constraint "ec_certificates_slug_locale_unique" unique ("slug", "locale"));

