PRAGMA foreign_keys = OFF;

-- 1. Tables
CREATE TABLE IF NOT EXISTS "ec_membership_plans" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "name" text default '' not null, "description" text, "price" real default 0.0 not null, "currency" text, "sale_price" real, "sale_start" text, "sale_end" text, "billing_period" text, "features" json, "limits" json, "sort_order" integer, constraint "ec_membership_plans_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_course_categories" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "name" text default '' not null, "description" text, "sort_order" integer, constraint "ec_course_categories_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_courses" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "title" text default '' not null, "excerpt" text, "description" text, "featured_image" text, "content" json, "category_id" text, "prerequisite_id" text, "access_level" text, "is_purchasable" integer, "required_plan_ids" json, "price" real, "currency" text, "sale_price" real, "sale_start" text, "sale_end" text, "duration_hours" real, "difficulty" text, "featured" integer, constraint "ec_courses_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_modules" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "title" text default '' not null, "course_id" text default '' not null, "description" text, "sort_order" integer, constraint "ec_modules_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_lessons" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "title" text default '' not null, "module_id" text default '' not null, "course_id" text default '' not null, "excerpt" text, "featured_image" text, "content" json, "summary" json, "video_url" text, "duration_minutes" integer, "sort_order" integer, "is_preview" integer, "prerequisite_id" text, "complexity" text, "resources" json, constraint "ec_lessons_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_quizzes" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "title" text default '' not null, "lesson_id" text default '' not null, "description" text, "passmark" integer, "pass_required" integer, "timer_minutes" integer, "allow_reset" integer, "random_order" integer, "grade_type" text, constraint "ec_quizzes_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_questions" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "quiz_id" text default '' not null, "question" text default '' not null, "question_image" text, "type" text, "answers" json, "grade" real, "sort_order" integer, "explanation" text, "random_order" integer, constraint "ec_questions_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_coupons" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "code" text default '' not null, "description" text, "type" text, "value" real default 0.0 not null, "applies_to" text, "applicable_ids" json, "usage_limit" integer, "usage_count" integer, "per_user_limit" integer, "min_purchase" real, "valid_from" text, "valid_until" text, constraint "ec_coupons_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_course_reviews" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "course_id" text default '' not null, "user_id" text default '' not null, "rating" integer default 0 not null, "title" text, "content" text, "verified_purchase" integer, "helpful_count" integer, constraint "ec_course_reviews_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_certificate_templates" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "name" text default '' not null, "description" text, "design" text default '' not null, "course_id" text, constraint "ec_certificate_templates_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_memberships" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "plan_id" text default '' not null, "membership_type" text, "started_at" text, "expires_at" text, "cancelled_at" text, "payment_provider" text, "subscription_id" text, constraint "ec_memberships_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_orders" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "type" text default '' not null, "item_id" text default '' not null, "subtotal" real, "discount_amount" real, "amount" real default 0.0 not null, "currency" text, "coupon_id" text, "coupon_code" text, "payment_provider" text, "payment_id" text, "metadata" json, constraint "ec_orders_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_enrollments" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "course_id" text default '' not null, "source" text default '' not null, "order_id" text, "progress" integer, "started_at" text, "completed_at" text, constraint "ec_enrollments_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_lesson_progress" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "lesson_id" text default '' not null, "course_id" text default '' not null, "completed" integer, "completed_at" text, "last_position" integer, constraint "ec_lesson_progress_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_quiz_submissions" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "quiz_id" text default '' not null, "lesson_id" text, "course_id" text, "score" real default 0.0 not null, "max_score" real default 0.0 not null, "percentage" real, "passed" integer, "answers" json, "started_at" text, "submitted_at" text, "time_spent_seconds" integer, constraint "ec_quiz_submissions_slug_locale_unique" unique ("slug", "locale"));

CREATE TABLE IF NOT EXISTS "ec_certificates" ("id" text primary key, "slug" text, "status" text default 'draft', "author_id" text, "primary_byline_id" text, "created_at" text default (datetime('now')), "updated_at" text default (datetime('now')), "published_at" text, "scheduled_at" text, "deleted_at" text, "version" integer default 1, "live_revision_id" text references "revisions" ("id"), "draft_revision_id" text references "revisions" ("id"), "locale" text default 'en' not null, "translation_group" text, "user_id" text default '' not null, "course_id" text default '' not null, "template_id" text default '' not null, "certificate_number" text default '' not null, "issued_at" text, "metadata" json, constraint "ec_certificates_slug_locale_unique" unique ("slug", "locale"));

-- 2. Collections
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3NQFS83YWJ4KVQ1098V61', 'coupons', 'Coupons', 'Coupon', 'ticket', '["drafts"]', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3NQDSV36ARRFVFDXJP9CA', 'course_categories', 'Course Categories', 'Category', 'folder', '["drafts"]', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3NQG2VJGTDSK015SCGG40', 'course_reviews', 'Course Reviews', 'Review', 'star', '["drafts"]', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3NQE7T2KYMMPXNVEZBA9Z', 'courses', 'Courses', 'Course', 'book-open', '["drafts","revisions","search","seo"]', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3Q4T9HJV1WPYHFSPZ4NNF', 'enrollments', 'Enrollments', 'Enrollment', 'book-open-check', '[]', 20, '2026-10-08 15:57:08', '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3NQEVYPVW6YHPF4Y33WJH', 'lessons', 'Lessons', 'Lesson', 'play-circle', '["drafts","revisions","search","seo"]', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3NQCD2BNKAG2DZJGMEJ59', 'membership_plans', 'Membership Plans', 'Plan', 'credit-card', '["drafts"]', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3NQEMREFNJJFWXX7B69Y9', 'modules', 'Modules', 'Module', 'folder', '["drafts"]', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3Q4T0GB3J575XECBWNNXJ', 'orders', 'Orders', 'Order', 'receipt', '[]', 20, '2026-10-08 15:57:08', '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3NQFF9AJA8ND29MGBP5Y1', 'questions', 'Questions', 'Question', 'help-circle', '["drafts"]', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_collections (id, slug, label, label_singular, icon, supports, sort_order, created_at, updated_at) VALUES ('01M4E3NQF62Q8J7W3EM46FFPW2', 'quizzes', 'Quizzes', 'Quiz', 'clipboard-list', '["drafts"]', 20, '2026-10-08 15:56:22', '2026-10-08 15:56:22');

-- 3. Fields
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCE56HGFZHF5B34EYPS', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'name', 'Plan Name', 'string', 'TEXT', 1, '', 0, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCEYHCZEG68X8HC3X34', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'description', 'Description', 'text', 'TEXT', 0, '', 1, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCEH244HQN47KG7S2HP', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'price', 'Price', 'number', 'REAL', 1, '{"min":0}', 2, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCETWQQCTHY6HPEQ2KG', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'currency', 'Currency', 'string', 'TEXT', 0, '', 3, '"USD"', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCEX3B2NDEJ5R29R257', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'sale_price', 'Sale Price', 'number', 'REAL', 0, '{"min":0}', 4, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCE4HNMCMZD99DRBPRD', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'sale_start', 'Sale Start', 'datetime', 'TEXT', 0, '', 5, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCE4DPXQGAK311YG4FA', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'sale_end', 'Sale End', 'datetime', 'TEXT', 0, '', 6, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCEG417P1JX5DF0VRA2', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'billing_period', 'Billing Period', 'string', 'TEXT', 0, '{"choices":["monthly","quarterly","yearly","lifetime"]}', 7, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCEYM8PB0E963WM614N', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'features', 'Features', 'json', 'JSON', 0, '', 8, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCEN5CARKQBNCTX3GEF', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'limits', 'Limits', 'json', 'JSON', 0, '', 9, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQCE7ABN9E8K4C7P72FM', '01M4E3NQCD2BNKAG2DZJGMEJ59', 'sort_order', 'Sort Order', 'integer', 'INTEGER', 0, '', 10, '0', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQDSEY0T2BB7XQ0Q69MD', '01M4E3NQDSV36ARRFVFDXJP9CA', 'name', 'Name', 'string', 'TEXT', 1, '', 0, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQDS72HTS81238MX6FCP', '01M4E3NQDSV36ARRFVFDXJP9CA', 'description', 'Description', 'text', 'TEXT', 0, '', 1, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQDSZFYFEJCDCNP3H263', '01M4E3NQDSV36ARRFVFDXJP9CA', 'sort_order', 'Sort Order', 'integer', 'INTEGER', 0, '', 2, '0', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE7E597W6HGXT77C302', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'title', 'Title', 'string', 'TEXT', 1, '', 0, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE77CEMVAYR00PEKNK9', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'excerpt', 'Excerpt', 'text', 'TEXT', 0, '', 1, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE7TXP6CEX49VJ8ZPMS', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'description', 'Description', 'text', 'TEXT', 0, '', 2, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE7MF8968FTFNNHH6HW', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'featured_image', 'Featured Image', 'image', 'TEXT', 0, '', 3, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE753PHANRPDGBM2JP6', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'content', 'Content', 'portableText', 'JSON', 0, '', 4, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE7SA0R7T79M0FFJ91Z', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'category_id', 'Category', 'reference', 'TEXT', 0, '{"collection":"course_categories"}', 5, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE7YWCNRJSRPA920HHZ', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'prerequisite_id', 'Prerequisite Course', 'reference', 'TEXT', 0, '{"collection":"courses"}', 6, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE7EG2P4ZZP5QNEQGQ8', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'access_level', 'Access Level', 'string', 'TEXT', 0, '{"choices":["free","membership","purchase"]}', 7, '"membership"', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE8QKKX0DSCSRZAR7ZN', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'is_purchasable', 'Individual Purchase', 'boolean', 'INTEGER', 0, '', 8, 'false', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE8SVGVVTFD7WXNVM8V', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'required_plan_ids', 'Required Plans', 'json', 'JSON', 0, '', 9, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE869F3HHYQ1CA6EKKK', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'price', 'Price', 'number', 'REAL', 0, '{"min":0}', 10, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE8A0M250YAJY906YJ7', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'currency', 'Currency', 'string', 'TEXT', 0, '', 11, '"USD"', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE8C58W8Y9V007YYDM8', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'sale_price', 'Sale Price', 'number', 'REAL', 0, '{"min":0}', 12, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE8P5F2JE2HD22TAN56', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'sale_start', 'Sale Start', 'datetime', 'TEXT', 0, '', 13, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE8QAAT8VDH9XFF9Y8N', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'sale_end', 'Sale End', 'datetime', 'TEXT', 0, '', 14, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE86J0XFHNF5CGDP1ZY', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'duration_hours', 'Duration (hours)', 'number', 'REAL', 0, '', 15, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE8S20ZB0HXCP1YNYMX', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'difficulty', 'Difficulty', 'string', 'TEXT', 0, '{"choices":["beginner","intermediate","advanced"]}', 16, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQE90E90WA0A3HQ1GZ2J', '01M4E3NQE7T2KYMMPXNVEZBA9Z', 'featured', 'Featured', 'boolean', 'INTEGER', 0, '', 17, 'false', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEM69BGZK6ZSPCDR1Z7', '01M4E3NQEMREFNJJFWXX7B69Y9', 'title', 'Title', 'string', 'TEXT', 1, '', 0, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEMJENE970B3DBQ85BX', '01M4E3NQEMREFNJJFWXX7B69Y9', 'course_id', 'Course', 'reference', 'TEXT', 1, '{"collection":"courses"}', 1, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEMME2S48K910CR7GVP', '01M4E3NQEMREFNJJFWXX7B69Y9', 'description', 'Description', 'text', 'TEXT', 0, '', 2, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEMBDAH3QT2DQB7PYQ3', '01M4E3NQEMREFNJJFWXX7B69Y9', 'sort_order', 'Sort Order', 'integer', 'INTEGER', 0, '', 3, '0', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEVHYHNH2GXJFH27RTC', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'title', 'Title', 'string', 'TEXT', 1, '', 0, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEV4N3837WQRT91434A', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'module_id', 'Module', 'reference', 'TEXT', 1, '{"collection":"modules"}', 1, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEVTGRH79RM7XWESAFJ', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'course_id', 'Course', 'reference', 'TEXT', 1, '{"collection":"courses"}', 2, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEV9031Z6Z6XHYZFGZ8', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'excerpt', 'Excerpt', 'text', 'TEXT', 0, '', 3, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEVQDZBQ7YTTZD0V925', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'featured_image', 'Featured Image', 'image', 'TEXT', 0, '', 4, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEWEM85B0FYWTPXJ9KN', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'content', 'Content', 'portableText', 'JSON', 0, '', 5, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEW4AZ6W6Z79EK1VZ8Q', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'summary', 'Summary', 'portableText', 'JSON', 0, '', 6, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEW8HKQMFTZTVFNPHN8', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'video_url', 'Video URL', 'string', 'TEXT', 0, '', 7, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEWYBT02Q5P46FWZMXB', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'duration_minutes', 'Duration (minutes)', 'integer', 'INTEGER', 0, '', 8, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEWS021A4WH84WREDHQ', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'sort_order', 'Sort Order', 'integer', 'INTEGER', 0, '', 9, '0', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEWS7J22M78XCHQF68J', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'is_preview', 'Free Preview', 'boolean', 'INTEGER', 0, '', 10, 'false', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEW014GF4S9VE08MH67', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'prerequisite_id', 'Prerequisite Lesson', 'reference', 'TEXT', 0, '{"collection":"lessons"}', 11, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEW392K257T9AHTBNXX', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'complexity', 'Complexity', 'string', 'TEXT', 0, '{"choices":["easy","medium","hard"]}', 12, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQEWTM4E7CMGYDY1XZCC', '01M4E3NQEVYPVW6YHPF4Y33WJH', 'resources', 'Resources', 'json', 'JSON', 0, '', 13, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQF6D3BT0FME65X9EK0G', '01M4E3NQF62Q8J7W3EM46FFPW2', 'title', 'Title', 'string', 'TEXT', 1, '', 0, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQF6YS5BZB7BR8ZMEZ7G', '01M4E3NQF62Q8J7W3EM46FFPW2', 'lesson_id', 'Lesson', 'reference', 'TEXT', 1, '{"collection":"lessons"}', 1, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQF6SKAN9JSVF33Z1MD9', '01M4E3NQF62Q8J7W3EM46FFPW2', 'description', 'Description', 'text', 'TEXT', 0, '', 2, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQF6X9Y6DGM5CEXCYBSZ', '01M4E3NQF62Q8J7W3EM46FFPW2', 'passmark', 'Pass Mark (%)', 'integer', 'INTEGER', 0, '{"min":0,"max":100}', 3, '70', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQF61QY7QSFFKZKQQNHE', '01M4E3NQF62Q8J7W3EM46FFPW2', 'pass_required', 'Pass Required', 'boolean', 'INTEGER', 0, '', 4, 'false', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQF6X94JV5Q00C7YM67Q', '01M4E3NQF62Q8J7W3EM46FFPW2', 'timer_minutes', 'Time Limit (minutes)', 'integer', 'INTEGER', 0, '{"min":0}', 5, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQF68WDBZ3AJPVDEETX8', '01M4E3NQF62Q8J7W3EM46FFPW2', 'allow_reset', 'Allow Retry', 'boolean', 'INTEGER', 0, '', 6, 'true', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQF6GR7EM797Q5WGT1MM', '01M4E3NQF62Q8J7W3EM46FFPW2', 'random_order', 'Randomize Questions', 'boolean', 'INTEGER', 0, '', 7, 'false', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQF64R90GBZ1YNV6K9QV', '01M4E3NQF62Q8J7W3EM46FFPW2', 'grade_type', 'Grading', 'string', 'TEXT', 0, '{"choices":["auto","manual"]}', 8, '"auto"', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFF1V163K28E9NFSXWZ', '01M4E3NQFF9AJA8ND29MGBP5Y1', 'quiz_id', 'Quiz', 'reference', 'TEXT', 1, '{"collection":"quizzes"}', 0, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFF3WZM3S84G9J7N87Z', '01M4E3NQFF9AJA8ND29MGBP5Y1', 'question', 'Question', 'text', 'TEXT', 1, '', 1, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFF31ZG1285J90SEPHQ', '01M4E3NQFF9AJA8ND29MGBP5Y1', 'question_image', 'Question Image', 'image', 'TEXT', 0, '', 2, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFF30JQNXS2HGGN85N3', '01M4E3NQFF9AJA8ND29MGBP5Y1', 'type', 'Type', 'string', 'TEXT', 0, '{"choices":["single","multiple","text","fill_blank"]}', 3, '"single"', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFFVCFMHPN9B3VNDCAY', '01M4E3NQFF9AJA8ND29MGBP5Y1', 'answers', 'Answers', 'json', 'JSON', 0, '', 4, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFF53QMRADKDCMEJ866', '01M4E3NQFF9AJA8ND29MGBP5Y1', 'grade', 'Points', 'number', 'REAL', 0, '', 5, '1', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFFDGJG6ES6WM8WP2YM', '01M4E3NQFF9AJA8ND29MGBP5Y1', 'sort_order', 'Sort Order', 'integer', 'INTEGER', 0, '', 6, '0', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFF6G1QS5JTAN2VRPPB', '01M4E3NQFF9AJA8ND29MGBP5Y1', 'explanation', 'Explanation', 'text', 'TEXT', 0, '', 7, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFFRKGQV3TS3VK3DQYZ', '01M4E3NQFF9AJA8ND29MGBP5Y1', 'random_order', 'Randomize Answers', 'boolean', 'INTEGER', 0, '', 8, 'false', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFS20GZ1WRB18VNZVFK', '01M4E3NQFS83YWJ4KVQ1098V61', 'code', 'Code', 'string', 'TEXT', 1, '', 0, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFS3C0830ET3C426A8T', '01M4E3NQFS83YWJ4KVQ1098V61', 'description', 'Description', 'text', 'TEXT', 0, '', 1, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFSPS345YPB8NHENJGD', '01M4E3NQFS83YWJ4KVQ1098V61', 'type', 'Type', 'string', 'TEXT', 0, '{"choices":["percentage","fixed"]}', 2, '"percentage"', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFS3J6CMFWWDX3AZYWD', '01M4E3NQFS83YWJ4KVQ1098V61', 'value', 'Value', 'number', 'REAL', 1, '{"min":0}', 3, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFSVQHE73XZMDHN87XV', '01M4E3NQFS83YWJ4KVQ1098V61', 'applies_to', 'Applies To', 'string', 'TEXT', 0, '{"choices":["all","membership","course"]}', 4, '"all"', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFSNXNG2YMS8CYSPCYZ', '01M4E3NQFS83YWJ4KVQ1098V61', 'applicable_ids', 'Specific Items', 'json', 'JSON', 0, '', 5, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFS121HJQ1MWFQBNXTA', '01M4E3NQFS83YWJ4KVQ1098V61', 'usage_limit', 'Usage Limit', 'integer', 'INTEGER', 0, '', 6, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFS0V9M0J8W6TJZVMQ0', '01M4E3NQFS83YWJ4KVQ1098V61', 'usage_count', 'Times Used', 'integer', 'INTEGER', 0, '', 7, '0', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFSXM9A005SDFRSKJTG', '01M4E3NQFS83YWJ4KVQ1098V61', 'per_user_limit', 'Per User Limit', 'integer', 'INTEGER', 0, '', 8, '1', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFSSTJTKP1YMYRPR0C9', '01M4E3NQFS83YWJ4KVQ1098V61', 'min_purchase', 'Min Purchase', 'number', 'REAL', 0, '{"min":0}', 9, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFS0E2N8G6E3JFV6GAC', '01M4E3NQFS83YWJ4KVQ1098V61', 'valid_from', 'Valid From', 'datetime', 'TEXT', 0, '', 10, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQFSDH6RR6TY18SGQM9W', '01M4E3NQFS83YWJ4KVQ1098V61', 'valid_until', 'Valid Until', 'datetime', 'TEXT', 0, '', 11, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQG2RMDWPQ78KS0XCPA8', '01M4E3NQG2VJGTDSK015SCGG40', 'course_id', 'Course', 'reference', 'TEXT', 1, '{"collection":"courses"}', 0, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQG2THTXXGKS378PVWPQ', '01M4E3NQG2VJGTDSK015SCGG40', 'user_id', 'User ID', 'string', 'TEXT', 1, '', 1, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQG2RQ0RRH2Z6D7F2Z1W', '01M4E3NQG2VJGTDSK015SCGG40', 'rating', 'Rating', 'integer', 'INTEGER', 1, '{"min":1,"max":5}', 2, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQG2QGPHZRNTNH5G8W4M', '01M4E3NQG2VJGTDSK015SCGG40', 'title', 'Title', 'string', 'TEXT', 0, '', 3, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQG2QTG658TVZW2KFRVD', '01M4E3NQG2VJGTDSK015SCGG40', 'content', 'Review', 'text', 'TEXT', 0, '', 4, NULL, '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQG2ESEJHDRTRYBR06EE', '01M4E3NQG2VJGTDSK015SCGG40', 'verified_purchase', 'Verified', 'boolean', 'INTEGER', 0, '', 5, 'false', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3NQG2RJD346D5VZTNVEJR', '01M4E3NQG2VJGTDSK015SCGG40', 'helpful_count', 'Helpful Votes', 'integer', 'INTEGER', 0, '', 6, '0', '2026-10-08 15:56:22');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T0YKVWG17F3KC1CEHA', '01M4E3Q4T0GB3J575XECBWNNXJ', 'user_id', 'User ID', 'string', 'TEXT', 1, '', 0, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T04Z6BNQZPQGCDJQ5P', '01M4E3Q4T0GB3J575XECBWNNXJ', 'type', 'Type', 'string', 'TEXT', 1, '{"choices":["membership","course"]}', 1, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T0ZG19S2JBZTS29W6X', '01M4E3Q4T0GB3J575XECBWNNXJ', 'item_id', 'Item ID', 'string', 'TEXT', 1, '', 2, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T081FPXSC1KYXZ0VNY', '01M4E3Q4T0GB3J575XECBWNNXJ', 'subtotal', 'Subtotal', 'number', 'REAL', 0, '', 3, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T0P1SVGPN4VMRD8YRK', '01M4E3Q4T0GB3J575XECBWNNXJ', 'discount_amount', 'Discount', 'number', 'REAL', 0, '', 4, '0', '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T1DBS7H23KW2AS1VMX', '01M4E3Q4T0GB3J575XECBWNNXJ', 'amount', 'Amount', 'number', 'REAL', 1, '', 5, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T1J2ES8QR5WP6DXPDQ', '01M4E3Q4T0GB3J575XECBWNNXJ', 'currency', 'Currency', 'string', 'TEXT', 0, '', 6, '"USD"', '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T1MJ6R6JPXG7RN7RWV', '01M4E3Q4T0GB3J575XECBWNNXJ', 'coupon_id', 'Coupon', 'reference', 'TEXT', 0, '{"collection":"coupons"}', 7, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T1XCAZC8RDJ2C6HD6B', '01M4E3Q4T0GB3J575XECBWNNXJ', 'coupon_code', 'Coupon Code', 'string', 'TEXT', 0, '', 8, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T1NM16MX54X8945HX4', '01M4E3Q4T0GB3J575XECBWNNXJ', 'payment_provider', 'Payment Provider', 'string', 'TEXT', 0, '', 9, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T163HV8KKEMFTQAP6B', '01M4E3Q4T0GB3J575XECBWNNXJ', 'payment_id', 'Payment ID', 'string', 'TEXT', 0, '', 10, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T12E32W3HZVNYQVZY9', '01M4E3Q4T0GB3J575XECBWNNXJ', 'metadata', 'Metadata', 'json', 'JSON', 0, '', 11, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4T97YQ99CBAN48B18DQ', '01M4E3Q4T9HJV1WPYHFSPZ4NNF', 'user_id', 'User ID', 'string', 'TEXT', 1, '', 0, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4TA07NT5K09WK4KXHR8', '01M4E3Q4T9HJV1WPYHFSPZ4NNF', 'course_id', 'Course', 'reference', 'TEXT', 1, '{"collection":"courses"}', 1, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4TASHXRXQ9NGTNG3YED', '01M4E3Q4T9HJV1WPYHFSPZ4NNF', 'source', 'Source', 'string', 'TEXT', 1, '{"choices":["membership","purchase"]}', 2, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4TAD3V96K9YHNKEP62C', '01M4E3Q4T9HJV1WPYHFSPZ4NNF', 'order_id', 'Order', 'reference', 'TEXT', 0, '{"collection":"orders"}', 3, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4TAW07CDDN01KVT2WSW', '01M4E3Q4T9HJV1WPYHFSPZ4NNF', 'progress', 'Progress %', 'integer', 'INTEGER', 0, '', 4, '0', '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4TAZYSJB4GCF7ZSTXH6', '01M4E3Q4T9HJV1WPYHFSPZ4NNF', 'started_at', 'Started At', 'datetime', 'TEXT', 0, '', 5, NULL, '2026-10-08 15:57:08');
INSERT OR REPLACE INTO _emdash_fields (id, collection_id, slug, label, type, column_type, required, options, sort_order, default_value, created_at) VALUES ('01M4E3Q4TAVH1G9TXP400AFE0Y', '01M4E3Q4T9HJV1WPYHFSPZ4NNF', 'completed_at', 'Completed At', 'datetime', 'TEXT', 0, '', 6, NULL, '2026-10-08 15:57:08');

-- Seed ec_course_categories
INSERT OR REPLACE INTO ec_course_categories ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "sort_order") VALUES ('01M4E3Q4WYP9MQ811GE3XMYZR0', 'basics', 'published', NULL, NULL, '2026-10-08T15:57:08.894Z', '2026-10-08T15:57:08.896Z', '2026-10-08T15:57:08.894Z', NULL, NULL, 2, '01M4E3Q4X0Y70KNJASRE5E0FGP', NULL, 'en', '01M4E3Q4WYP9MQ811GE3XMYZR0', 'Basics', 'Foundational courses', 0);
INSERT OR REPLACE INTO ec_course_categories ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "sort_order") VALUES ('01M4E3Q4X2DXKN9ETMRZ8AEP22', 'advanced', 'published', NULL, NULL, '2026-10-08T15:57:08.898Z', '2026-10-08T15:57:08.899Z', '2026-10-08T15:57:08.898Z', NULL, NULL, 2, '01M4E3Q4X3BG56F042ZCY90ETC', NULL, 'en', '01M4E3Q4X2DXKN9ETMRZ8AEP22', 'Advanced', 'Advanced topics', 1);
INSERT OR REPLACE INTO ec_course_categories ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "sort_order") VALUES ('cat_intro', 'nhap-mon-vo-long', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'cat_intro', 'Nhập Môn & Vỡ Lòng', 'Khóa học dành cho các bạn nhỏ và người mới bắt đầu làm quen với cờ vua.', 1);
INSERT OR REPLACE INTO ec_course_categories ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "sort_order") VALUES ('cat_opening', 'khai-cuoc-chuan', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'cat_opening', 'Khai Cuộc Chuẩn', 'Các hệ thống khai cuộc bài bản, làm chủ trung tâm và bẫy khai cuộc.', 2);
INSERT OR REPLACE INTO ec_course_categories ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "sort_order") VALUES ('cat_tactics', 'chien-thuat-don-phoi-hop', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'cat_tactics', 'Chiến Thuật & Đòn Phối Hợp', 'Rèn luyện khả năng quan sát và tính toán các đòn chiến thuật sắc bén.', 3);
INSERT OR REPLACE INTO ec_course_categories ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "sort_order") VALUES ('cat_endgame', 'tan-cuoc-kinh-dien', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'cat_endgame', 'Tàn Cuộc Kinh Điển', 'Kỹ thuật tàn cuộc Xe, Tốt căn bản giúp chuyển hóa ưu thế thành chiến thắng.', 4);

-- Seed ec_membership_plans
INSERT OR REPLACE INTO ec_membership_plans ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "price", "currency", "sale_price", "sale_start", "sale_end", "billing_period", "features", "limits", "sort_order") VALUES ('01M4E3Q4VSF9TQHACFPVAS3G0B', 'free', 'published', NULL, NULL, '2026-10-08T15:57:08.857Z', '2026-10-08T15:57:08.876Z', '2026-10-08T15:57:08.857Z', NULL, NULL, 2, '01M4E3Q4WDR5CEG7X6S2P6JSQ5', NULL, 'en', '01M4E3Q4VSF9TQHACFPVAS3G0B', 'Free', 'Access to free courses only', 0, 'USD', NULL, NULL, NULL, 'lifetime', '["Access to free courses","Community forum access"]', '{"courses":"free_only"}', 0);
INSERT OR REPLACE INTO ec_membership_plans ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "price", "currency", "sale_price", "sale_start", "sale_end", "billing_period", "features", "limits", "sort_order") VALUES ('01M4E3Q4WNV9QHCMJ2X3888NBH', 'basic', 'published', NULL, NULL, '2026-10-08T15:57:08.885Z', '2026-10-08T15:57:08.886Z', '2026-10-08T15:57:08.885Z', NULL, NULL, 2, '01M4E3Q4WQSMTXDHPHDWEWZX2B', NULL, 'en', '01M4E3Q4WNV9QHCMJ2X3888NBH', 'Basic', 'Access to basic course library', 9.99, 'USD', NULL, NULL, NULL, 'monthly', '["All free courses","Basic course library","Email support"]', '{"courses":"basic"}', 1);
INSERT OR REPLACE INTO ec_membership_plans ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "price", "currency", "sale_price", "sale_start", "sale_end", "billing_period", "features", "limits", "sort_order") VALUES ('01M4E3Q4WS3ED7BYVAW70TSNJ8', 'pro', 'published', NULL, NULL, '2026-10-08T15:57:08.889Z', '2026-10-08T15:57:08.890Z', '2026-10-08T15:57:08.889Z', NULL, NULL, 2, '01M4E3Q4WTP8W1A0MFZD68E8QS', NULL, 'en', '01M4E3Q4WS3ED7BYVAW70TSNJ8', 'Pro', 'Full access to all courses', 29.99, 'USD', 19.99, NULL, NULL, 'monthly', '["All courses","Certificates","Priority support","Downloadable resources"]', '{"courses":"all","downloads":true,"certificates":true}', 2);
INSERT OR REPLACE INTO ec_membership_plans ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "price", "currency", "sale_price", "sale_start", "sale_end", "billing_period", "features", "limits", "sort_order") VALUES ('plan_monthly', 'goi-thanh-vien-thang', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'plan_monthly', 'Gói Hội Viên Tháng', 'Truy cập toàn bộ thư viện khóa học cơ bản & luyện tập thế cờ hàng ngày.', 99000, 'VND', NULL, NULL, NULL, 'tháng', '["Truy cập hơn 20+ khóa học cờ vua nền tảng","Luyện tập 1.000+ câu đố thế cờ có hướng dẫn","Tham gia giải đấu online học đường hàng tuần","Giải đáp thắc mắc chuyên môn trong cộng đồng"]', NULL, 1);
INSERT OR REPLACE INTO ec_membership_plans ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "price", "currency", "sale_price", "sale_start", "sale_end", "billing_period", "features", "limits", "sort_order") VALUES ('plan_yearly', 'goi-hoi-vien-nam-tiet-kiem', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'plan_yearly', 'Gói Hội Viên Năm (Tiết Kiệm 30%)', 'Lộ trình học cờ vua toàn diện 1 năm cho học sinh & phụ huynh đồng hành.', 899000, 'VND', 699000, NULL, NULL, 'năm', '["Toàn bộ đặc quyền của gói Hội Viên Tháng","Tiết kiệm hơn 30% học phí so với trả theo tháng","Mở khóa toàn bộ khóa Khai cuộc & Chiến thuật nâng cao","Huấn luyện viên chấm và phân tích 2 ván đấu/tháng","Chứng chỉ hoàn thành cấp độ từ Cờ Vua Học Đường"]', NULL, 2);
INSERT OR REPLACE INTO ec_membership_plans ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "name", "description", "price", "currency", "sale_price", "sale_start", "sale_end", "billing_period", "features", "limits", "sort_order") VALUES ('plan_vip_lifetime', 'goi-vip-hoc-duong-tron-doi', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'plan_vip_lifetime', 'Gói VIP Học Đường Trọn Đời', 'Gói huấn luyện và tài khoản trọn đời đồng hành phát triển tài năng nhí.', 2490000, 'VND', 1990000, NULL, NULL, 'trọn đời', '["Mở khóa TOÀN BỘ khóa học hiện tại & tương lai","Tặng 3 buổi kèm 1-1 trực tuyến cùng Kiện tướng/HLV Quốc gia","Tặng 01 bộ cờ vua tiêu chuẩn thi đấu giao tận nhà","Ưu tiên hỗ trợ sư phạm và định hướng thi đấu giải trẻ"]', NULL, 3);

-- Seed ec_courses
INSERT OR REPLACE INTO ec_courses ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "excerpt", "description", "featured_image", "content", "category_id", "prerequisite_id", "access_level", "is_purchasable", "required_plan_ids", "price", "currency", "sale_price", "sale_start", "sale_end", "duration_hours", "difficulty", "featured") VALUES ('01M4E3Q4X5B88XB60QG4HRZT32', 'getting-started', 'published', NULL, NULL, '2026-10-08T15:57:08.901Z', '2026-10-08T15:57:08.903Z', '2026-10-08T15:57:08.901Z', NULL, NULL, 2, '01M4E3Q4X7XQBWACXPVFVJF645', NULL, 'en', '01M4E3Q4X5B88XB60QG4HRZT32', 'Getting Started', 'Introduction to our learning platform', 'Learn how to navigate and use the platform effectively', NULL, NULL, 'cat-basics', NULL, 'free', 0, NULL, NULL, NULL, NULL, NULL, NULL, 1, 'beginner', 1);
INSERT OR REPLACE INTO ec_courses ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "excerpt", "description", "featured_image", "content", "category_id", "prerequisite_id", "access_level", "is_purchasable", "required_plan_ids", "price", "currency", "sale_price", "sale_start", "sale_end", "duration_hours", "difficulty", "featured") VALUES ('01M4E3Q4XAFG1JQ70ARBTQVD0X', 'fundamentals', 'published', NULL, NULL, '2026-10-08T15:57:08.906Z', '2026-10-08T15:57:08.908Z', '2026-10-08T15:57:08.906Z', NULL, NULL, 2, '01M4E3Q4XCEA2HW6NXTAX71KGX', NULL, 'en', '01M4E3Q4XAFG1JQ70ARBTQVD0X', 'Fundamentals Course', 'Core concepts and foundations', 'Master the fundamental concepts', NULL, NULL, 'cat-basics', NULL, 'membership', 1, '["plan-basic","plan-pro"]', 49.99, 'USD', NULL, NULL, NULL, 5, 'beginner', NULL);
INSERT OR REPLACE INTO ec_courses ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "excerpt", "description", "featured_image", "content", "category_id", "prerequisite_id", "access_level", "is_purchasable", "required_plan_ids", "price", "currency", "sale_price", "sale_start", "sale_end", "duration_hours", "difficulty", "featured") VALUES ('course_chess_intro', 'nhap-mon-co-vua-cho-nguoi-moi-bat-dau', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'course_chess_intro', 'Nhập Môn Cờ Vua: Tự Tin Đi Nước Cờ Đầu Tiên', 'Khóa học nền tảng từ quy tắc bàn cờ, cách di chuyển các quân đến những đòn phối hợp căn bản nhất.', 'Khóa học được thiết kế đặc biệt cho học sinh và người mới bắt đầu.', 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?w=800&auto=format&fit=crop&q=80', NULL, 'cat_intro', NULL, 'free', 1, NULL, 199000, 'VND', 149000, NULL, NULL, 2.5, 'beginner', 1);
INSERT OR REPLACE INTO ec_courses ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "excerpt", "description", "featured_image", "content", "category_id", "prerequisite_id", "access_level", "is_purchasable", "required_plan_ids", "price", "currency", "sale_price", "sale_start", "sale_end", "duration_hours", "difficulty", "featured") VALUES ('course_chess_tactics', '100-don-chien-thuat-chieu-het-kinh-dien', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'course_chess_tactics', '100 Đòn Chiến Thuật & Phối Hợp Chiếu Hết Kinh Điển', 'Luyện mắt chiến thuật qua 100 dạng thế cờ: Đòn bắt đôi, găm quân, giương đông kích tây và chiếu bí bất ngờ.', 'Chiến thuật là linh hồn của ván cờ. Khóa học giúp bạn tìm ra nước đi sát thương nhất.', 'https://images.unsplash.com/photo-1586165368502-1bad197a6461?w=800&auto=format&fit=crop&q=80', NULL, 'cat_tactics', NULL, 'paid', 1, NULL, 399000, 'VND', 299000, NULL, NULL, 4, 'intermediate', 1);
INSERT OR REPLACE INTO ec_courses ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "excerpt", "description", "featured_image", "content", "category_id", "prerequisite_id", "access_level", "is_purchasable", "required_plan_ids", "price", "currency", "sale_price", "sale_start", "sale_end", "duration_hours", "difficulty", "featured") VALUES ('course_chess_opening_italian', 'bi-quyet-khai-cuoc-italian-va-bay-khai-cuoc', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'course_chess_opening_italian', 'Bí Quyết Khai Cuộc Italian & Bẫy Khai Cuộc Học Đường', 'Chinh phục Khai cuộc Ý (Giuoco Piano & Evans Gambit), phát triển quân thần tốc và bảo vệ Vua vững chắc.', 'Khai cuộc Ý là hệ thống khai cuộc phổ biến và hiệu quả nhất cho các kỳ thủ học đường.', 'https://images.unsplash.com/photo-1560174038-da43ac74f01b?w=800&auto=format&fit=crop&q=80', NULL, 'cat_opening', NULL, 'membership', 1, NULL, 499000, 'VND', 349000, NULL, NULL, 5.5, 'intermediate', 1);
INSERT OR REPLACE INTO ec_courses ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "excerpt", "description", "featured_image", "content", "category_id", "prerequisite_id", "access_level", "is_purchasable", "required_plan_ids", "price", "currency", "sale_price", "sale_start", "sale_end", "duration_hours", "difficulty", "featured") VALUES ('course_chess_endgame_rook', 'tuyet-ky-co-tan-xe-tot-can-ban-den-chuyen-sau', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'course_chess_endgame_rook', 'Tuyệt Kỹ Cờ Tàn Xe & Tốt: Căn Bản Đến Chuyên Sâu', 'Nắm chắc các thế cờ tàn mẫu mực (Lucena, Philidor) giúp chuyển hóa ưu thế thành chiến thắng tuyệt đối.', '90% các ván cờ đều dẫn đến tàn cuộc Xe. Nắm vững kỹ thuật để làm chủ ván đấu.', 'https://images.unsplash.com/photo-1580541832626-2a7131ee809f?w=800&auto=format&fit=crop&q=80', NULL, 'cat_endgame', NULL, 'paid', 1, NULL, 450000, 'VND', 350000, NULL, NULL, 3.5, 'advanced', 0);

-- Seed ec_modules
INSERT OR REPLACE INTO ec_modules ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "course_id", "description", "sort_order") VALUES ('01M4E3Q4XEC83BCK882ZMR8WFE', 'introduction', 'published', NULL, NULL, '2026-10-08T15:57:08.910Z', '2026-10-08T15:57:08.912Z', '2026-10-08T15:57:08.910Z', NULL, NULL, 2, '01M4E3Q4XGWYE2JPRP5SGW3FEW', NULL, 'en', '01M4E3Q4XEC83BCK882ZMR8WFE', 'Introduction', 'course-getting-started', 'Welcome and platform overview', 0);
INSERT OR REPLACE INTO ec_modules ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "course_id", "description", "sort_order") VALUES ('01M4E3Q4XKJ82QZFX1EXX54RA6', 'basics', 'published', NULL, NULL, '2026-10-08T15:57:08.915Z', '2026-10-08T15:57:08.917Z', '2026-10-08T15:57:08.915Z', NULL, NULL, 2, '01M4E3Q4XN3CH2NG6MZQSGM87J', NULL, 'en', '01M4E3Q4XKJ82QZFX1EXX54RA6', 'The Basics', 'course-getting-started', 'Core features walkthrough', 1);
INSERT OR REPLACE INTO ec_modules ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "course_id", "description", "sort_order") VALUES ('mod_intro_1', 'lam-quen-ban-co-va-quan-co', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'mod_intro_1', 'Phần 1: Bàn Cờ & Cách Đi Các Quân', 'course_chess_intro', NULL, 1);
INSERT OR REPLACE INTO ec_modules ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "course_id", "description", "sort_order") VALUES ('mod_intro_2', 'cac-nuoc-di-dac-biet-va-luat-choi', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'mod_intro_2', 'Phần 2: Nước Đi Đặc Biệt & Luật Kết Thúc', 'course_chess_intro', NULL, 2);
INSERT OR REPLACE INTO ec_modules ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "course_id", "description", "sort_order") VALUES ('mod_tac_1', 'don-tan-cong-doi-va-gam-quan', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'mod_tac_1', 'Chương 1: Đòn Tấn Công Đôi & Giằng Quân', 'course_chess_tactics', NULL, 1);
INSERT OR REPLACE INTO ec_modules ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "course_id", "description", "sort_order") VALUES ('mod_tac_2', 'don-chieu-bi-dac-sac', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'mod_tac_2', 'Chương 2: Các Hình Mẫu Chiếu Hết Điển Hình', 'course_chess_tactics', NULL, 2);

-- Seed ec_lessons
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('01M4E3Q4XQYZ4J01J77VF0ERVD', 'welcome', 'published', NULL, NULL, '2026-10-08T15:57:08.920Z', '2026-10-08T15:57:08.921Z', '2026-10-08T15:57:08.919Z', NULL, NULL, 2, '01M4E3Q4XSQC8HWG9VJ2DNA019', NULL, 'en', '01M4E3Q4XQYZ4J01J77VF0ERVD', 'Welcome to the Platform', 'module-intro', 'course-getting-started', 'Your first steps', NULL, NULL, NULL, NULL, 5, 0, 1, NULL, 'easy', '[{"type":"pdf","title":"Welcome Guide","url":"/resources/welcome-guide.pdf"}]');
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('01M4E3Q4XWXQ5JN93JD53ZP7CV', 'platform-navigation', 'published', NULL, NULL, '2026-10-08T15:57:08.924Z', '2026-10-08T15:57:08.925Z', '2026-10-08T15:57:08.924Z', NULL, NULL, 2, '01M4E3Q4XXZ0PKE6D91K6A6X6Y', NULL, 'en', '01M4E3Q4XWXQ5JN93JD53ZP7CV', 'Navigating the Platform', 'module-intro', 'course-getting-started', NULL, NULL, NULL, NULL, NULL, 10, 1, 1, NULL, 'easy', NULL);
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('les_intro_1_1', 'ban-co-toa-do-va-cach-xep-quan', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'les_intro_1_1', 'Bài 1: Bàn cờ, hệ tọa độ và cách xếp quân chuẩn', 'mod_intro_1', 'course_chess_intro', NULL, NULL, NULL, NULL, 'https://www.youtube.com/embed/fKxG8KjH1RE', 15, 1, 1, NULL, NULL, NULL);
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('les_intro_1_2', 'cach-di-va-an-quan-tot-xe-ma-tuong', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'les_intro_1_2', 'Bài 2: Cách di chuyển và ăn quân của Tốt, Xe, Mã, Tượng', 'mod_intro_1', 'course_chess_intro', NULL, NULL, NULL, NULL, 'https://www.youtube.com/embed/fKxG8KjH1RE', 20, 2, 1, NULL, NULL, NULL);
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('les_intro_1_3', 'suc-manh-cua-hau-va-su-an-toan-cua-vua', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'les_intro_1_3', 'Bài 3: Sức mạnh bá chủ của Hậu và bảo vệ Vua', 'mod_intro_1', 'course_chess_intro', NULL, NULL, NULL, NULL, '', 18, 3, 0, NULL, NULL, NULL);
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('les_intro_2_1', 'ky-thuat-nhap-thanh-an-toan', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'les_intro_2_1', 'Bài 4: Nhập thành cánh Vua & Cánh Hậu đúng luật', 'mod_intro_2', 'course_chess_intro', NULL, NULL, NULL, NULL, '', 15, 1, 0, NULL, NULL, NULL);
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('les_intro_2_2', 'bat-tot-qua-duong-va-phong-cap', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'les_intro_2_2', 'Bài 5: Bắt tốt qua đường (En Passant) và Phong cấp', 'mod_intro_2', 'course_chess_intro', NULL, NULL, NULL, NULL, '', 15, 2, 0, NULL, NULL, NULL);
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('les_intro_2_3', 'chieu-chieu-het-va-hoa-co-stalemate', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'les_intro_2_3', 'Bài 6: Phân biệt Chiếu, Chiếu Hết và Hòa Cờ (Stalemate)', 'mod_intro_2', 'course_chess_intro', NULL, NULL, NULL, NULL, '', 25, 3, 0, NULL, NULL, NULL);
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('les_tac_1_1', 'nghe-thuat-chia-doi-cua-ma-va-hau', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'les_tac_1_1', 'Bài 1: Tuyệt chiêu Chĩa Đôi (Fork) của quân Mã & Hậu', 'mod_tac_1', 'course_chess_tactics', NULL, NULL, NULL, NULL, 'https://www.youtube.com/embed/fKxG8KjH1RE', 25, 1, 1, NULL, NULL, NULL);
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('les_tac_1_2', 'don-giang-quan-pin-va-cach-hoa-giai', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'les_tac_1_2', 'Bài 2: Đòn Giằng Quân (Pin) tuyệt đối & tương đối', 'mod_tac_1', 'course_chess_tactics', NULL, NULL, NULL, NULL, '', 30, 2, 0, NULL, NULL, NULL);
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('les_tac_2_1', 'chieu-that-smothered-mate-huyen-thoai', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'les_tac_2_1', 'Bài 3: Đòn Chiếu Thắt (Smothered Mate) nghẹt thở', 'mod_tac_2', 'course_chess_tactics', NULL, NULL, NULL, NULL, '', 20, 1, 0, NULL, NULL, NULL);
INSERT OR REPLACE INTO ec_lessons ("id", "slug", "status", "author_id", "primary_byline_id", "created_at", "updated_at", "published_at", "scheduled_at", "deleted_at", "version", "live_revision_id", "draft_revision_id", "locale", "translation_group", "title", "module_id", "course_id", "excerpt", "featured_image", "content", "summary", "video_url", "duration_minutes", "sort_order", "is_preview", "prerequisite_id", "complexity", "resources") VALUES ('les_tac_2_2', 'chieu-het-hang-day-back-rank-mate', 'published', NULL, NULL, '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', '2026-10-08T15:59:31.934Z', NULL, NULL, 1, NULL, NULL, 'en', 'les_tac_2_2', 'Bài 4: Bẫy Chiếu Hết Hàng Ngang Đáy (Back-rank Mate)', 'mod_tac_2', 'course_chess_tactics', NULL, NULL, NULL, NULL, '', 20, 2, 0, NULL, NULL, NULL);

PRAGMA foreign_keys = ON;
