import type { CreateCollectionInput, CreateFieldInput } from "emdash";

export interface LmsCollectionDefinition extends CreateCollectionInput {
	fields: CreateFieldInput[];
}

export const LMS_COLLECTIONS: LmsCollectionDefinition[] = [
	{
		slug: "membership_plans",
		label: "Membership Plans",
		labelSingular: "Plan",
		description: "Subscription tiers and library pass plans",
		icon: "credit-card",
		supports: ["drafts"],
		sortOrder: 20,
		fields: [
			{ slug: "name", label: "Plan Name", type: "string", required: true },
			{ slug: "description", label: "Description", type: "text" },
			{ slug: "price", label: "Price", type: "number", required: true, options: { min: 0 } },
			{ slug: "currency", label: "Currency", type: "string", defaultValue: "VND" },
			{ slug: "sale_price", label: "Sale Price", type: "number", options: { min: 0 } },
			{ slug: "sale_start", label: "Sale Start", type: "datetime" },
			{ slug: "sale_end", label: "Sale End", type: "datetime" },
			{
				slug: "billing_period",
				label: "Billing Period",
				type: "select",
				validation: { options: ["monthly", "quarterly", "yearly", "lifetime"] },
			},
			{ slug: "features", label: "Features", type: "json" },
			{ slug: "limits", label: "Limits", type: "json" },
			{ slug: "sort_order", label: "Sort Order", type: "integer", defaultValue: 0 },
		],
	},
	{
		slug: "course_categories",
		label: "Course Categories",
		labelSingular: "Category",
		description: "Categories for organizing chess courses",
		icon: "folder",
		supports: ["drafts"],
		sortOrder: 20,
		fields: [
			{ slug: "name", label: "Name", type: "string", required: true },
			{ slug: "description", label: "Description", type: "text" },
			{ slug: "sort_order", label: "Sort Order", type: "integer", defaultValue: 0 },
		],
	},
	{
		slug: "courses",
		label: "Courses",
		labelSingular: "Course",
		description: "Structured chess courses with modules and lessons",
		icon: "book-open",
		supports: ["drafts", "revisions", "search", "seo"],
		sortOrder: 20,
		fields: [
			{ slug: "title", label: "Title", type: "string", required: true, searchable: true },
			{ slug: "excerpt", label: "Excerpt", type: "text", searchable: true },
			{ slug: "description", label: "Description", type: "text" },
			{ slug: "featured_image", label: "Featured Image", type: "image" },
			{ slug: "content", label: "Content", type: "portableText", searchable: true },
			{
				slug: "category_id",
				label: "Category",
				type: "reference",
				options: { collection: "course_categories" },
			},
			{
				slug: "prerequisite_id",
				label: "Prerequisite Course",
				type: "reference",
				options: { collection: "courses" },
			},
			{
				slug: "access_level",
				label: "Access Level",
				type: "select",
				validation: { options: ["free", "membership", "purchase"] },
				defaultValue: "membership",
			},
			{
				slug: "is_purchasable",
				label: "Individual Purchase",
				type: "boolean",
				defaultValue: false,
			},
			{ slug: "required_plan_ids", label: "Required Plans", type: "json" },
			{ slug: "price", label: "Price", type: "number", options: { min: 0 } },
			{ slug: "currency", label: "Currency", type: "string", defaultValue: "VND" },
			{ slug: "sale_price", label: "Sale Price", type: "number", options: { min: 0 } },
			{ slug: "sale_start", label: "Sale Start", type: "datetime" },
			{ slug: "sale_end", label: "Sale End", type: "datetime" },
			{ slug: "duration_hours", label: "Duration (hours)", type: "number" },
			{
				slug: "difficulty",
				label: "Difficulty",
				type: "select",
				validation: { options: ["beginner", "intermediate", "advanced"] },
			},
			{ slug: "featured", label: "Featured", type: "boolean", defaultValue: false },
		],
	},
	{
		slug: "modules",
		label: "Modules",
		labelSingular: "Module",
		description: "Course sections / chapters",
		icon: "folder",
		supports: ["drafts"],
		sortOrder: 20,
		fields: [
			{ slug: "title", label: "Title", type: "string", required: true },
			{
				slug: "course_id",
				label: "Course",
				type: "reference",
				options: { collection: "courses" },
				required: true,
			},
			{ slug: "description", label: "Description", type: "text" },
			{ slug: "sort_order", label: "Sort Order", type: "integer", defaultValue: 0 },
		],
	},
	{
		slug: "lessons",
		label: "Lessons",
		labelSingular: "Lesson",
		description: "Individual learning units within a module",
		icon: "play-circle",
		supports: ["drafts", "revisions", "search", "seo"],
		sortOrder: 20,
		fields: [
			{ slug: "title", label: "Title", type: "string", required: true, searchable: true },
			{
				slug: "module_id",
				label: "Module",
				type: "reference",
				options: { collection: "modules" },
				required: true,
			},
			{
				slug: "course_id",
				label: "Course",
				type: "reference",
				options: { collection: "courses" },
				required: true,
			},
			{ slug: "excerpt", label: "Excerpt", type: "text" },
			{ slug: "featured_image", label: "Featured Image", type: "image" },
			{ slug: "content", label: "Content", type: "portableText", searchable: true },
			{ slug: "summary", label: "Summary", type: "portableText" },
			{ slug: "video_url", label: "Video URL", type: "string" },
			{ slug: "duration_minutes", label: "Duration (minutes)", type: "integer" },
			{ slug: "sort_order", label: "Sort Order", type: "integer", defaultValue: 0 },
			{ slug: "is_preview", label: "Free Preview", type: "boolean", defaultValue: false },
			{
				slug: "prerequisite_id",
				label: "Prerequisite Lesson",
				type: "reference",
				options: { collection: "lessons" },
			},
			{
				slug: "complexity",
				label: "Complexity",
				type: "select",
				validation: { options: ["easy", "medium", "hard"] },
			},
			{ slug: "resources", label: "Resources", type: "json" },
		],
	},
	{
		slug: "quizzes",
		label: "Quizzes",
		labelSingular: "Quiz",
		description: "Quizzes attached to lessons or courses",
		icon: "clipboard-list",
		supports: ["drafts"],
		sortOrder: 20,
		fields: [
			{ slug: "title", label: "Title", type: "string", required: true },
			{
				slug: "lesson_id",
				label: "Lesson",
				type: "reference",
				options: { collection: "lessons" },
				required: true,
			},
			{ slug: "description", label: "Description", type: "text" },
			{
				slug: "passmark",
				label: "Pass Mark (%)",
				type: "integer",
				defaultValue: 70,
				options: { min: 0, max: 100 },
			},
			{ slug: "pass_required", label: "Pass Required", type: "boolean", defaultValue: false },
			{
				slug: "timer_minutes",
				label: "Time Limit (minutes)",
				type: "integer",
				options: { min: 0 },
			},
			{ slug: "allow_reset", label: "Allow Retry", type: "boolean", defaultValue: true },
			{ slug: "random_order", label: "Randomize Questions", type: "boolean", defaultValue: false },
			{
				slug: "grade_type",
				label: "Grading",
				type: "select",
				validation: { options: ["auto", "manual"] },
				defaultValue: "auto",
			},
		],
	},
	{
		slug: "questions",
		label: "Questions",
		labelSingular: "Question",
		description: "Individual questions within a quiz",
		icon: "help-circle",
		supports: ["drafts"],
		sortOrder: 20,
		fields: [
			{
				slug: "quiz_id",
				label: "Quiz",
				type: "reference",
				options: { collection: "quizzes" },
				required: true,
			},
			{ slug: "question", label: "Question", type: "text", required: true },
			{ slug: "question_image", label: "Question Image", type: "image" },
			{
				slug: "type",
				label: "Type",
				type: "select",
				validation: { options: ["single", "multiple", "text", "fill_blank"] },
				defaultValue: "single",
			},
			{ slug: "answers", label: "Answers", type: "json" },
			{ slug: "grade", label: "Points", type: "number", defaultValue: 1 },
			{ slug: "sort_order", label: "Sort Order", type: "integer", defaultValue: 0 },
			{ slug: "explanation", label: "Explanation", type: "text" },
			{ slug: "random_order", label: "Randomize Answers", type: "boolean", defaultValue: false },
		],
	},
	{
		slug: "coupons",
		label: "Coupons",
		labelSingular: "Coupon",
		description: "Discount coupons for courses and memberships",
		icon: "ticket",
		supports: ["drafts"],
		sortOrder: 20,
		fields: [
			{ slug: "code", label: "Code", type: "string", required: true, unique: true },
			{ slug: "description", label: "Description", type: "text" },
			{
				slug: "type",
				label: "Type",
				type: "select",
				validation: { options: ["percentage", "fixed"] },
				defaultValue: "percentage",
			},
			{ slug: "value", label: "Value", type: "number", required: true, options: { min: 0 } },
			{
				slug: "applies_to",
				label: "Applies To",
				type: "select",
				validation: { options: ["all", "membership", "course"] },
				defaultValue: "all",
			},
			{ slug: "applicable_ids", label: "Specific Items", type: "json" },
			{ slug: "usage_limit", label: "Usage Limit", type: "integer" },
			{ slug: "usage_count", label: "Times Used", type: "integer", defaultValue: 0 },
			{ slug: "per_user_limit", label: "Per User Limit", type: "integer", defaultValue: 1 },
			{ slug: "min_purchase", label: "Min Purchase", type: "number", options: { min: 0 } },
			{ slug: "valid_from", label: "Valid From", type: "datetime" },
			{ slug: "valid_until", label: "Valid Until", type: "datetime" },
		],
	},
	{
		slug: "course_reviews",
		label: "Course Reviews",
		labelSingular: "Review",
		description: "Student reviews and ratings for courses",
		icon: "star",
		supports: ["drafts"],
		sortOrder: 20,
		fields: [
			{
				slug: "course_id",
				label: "Course",
				type: "reference",
				options: { collection: "courses" },
				required: true,
			},
			{ slug: "user_id", label: "User ID", type: "string", required: true },
			{
				slug: "rating",
				label: "Rating",
				type: "integer",
				required: true,
				options: { min: 1, max: 5 },
			},
			{ slug: "title", label: "Title", type: "string" },
			{ slug: "content", label: "Review", type: "text" },
			{ slug: "verified_purchase", label: "Verified", type: "boolean", defaultValue: false },
			{ slug: "helpful_count", label: "Helpful Votes", type: "integer", defaultValue: 0 },
		],
	},
	{
		slug: "certificate_templates",
		label: "Certificate Templates",
		labelSingular: "Template",
		description: "SVG/HTML templates for course completion certificates",
		icon: "award",
		supports: ["drafts"],
		sortOrder: 20,
		fields: [
			{ slug: "name", label: "Name", type: "string", required: true },
			{ slug: "description", label: "Description", type: "text" },
			{ slug: "design", label: "Design (HTML/SVG)", type: "text", required: true },
			{
				slug: "course_id",
				label: "Course (optional)",
				type: "reference",
				options: { collection: "courses" },
			},
		],
	},
	{
		slug: "memberships",
		label: "Memberships",
		labelSingular: "Membership",
		description: "Active and past user library card subscriptions",
		icon: "user-check",
		sortOrder: 20,
		fields: [
			{ slug: "user_id", label: "User ID", type: "string", required: true },
			{
				slug: "plan_id",
				label: "Plan",
				type: "reference",
				options: { collection: "membership_plans" },
				required: true,
			},
			{
				slug: "membership_type",
				label: "Type",
				type: "select",
				validation: { options: ["free", "loyalty"] },
				defaultValue: "free",
			},
			{ slug: "started_at", label: "Started At", type: "datetime" },
			{ slug: "expires_at", label: "Expires At", type: "datetime" },
			{ slug: "cancelled_at", label: "Cancelled At", type: "datetime" },
			{ slug: "payment_provider", label: "Payment Provider", type: "string" },
			{ slug: "subscription_id", label: "Subscription ID", type: "string" },
		],
	},
	{
		slug: "orders",
		label: "Orders",
		labelSingular: "Order",
		description: "Purchase records for memberships and courses",
		icon: "receipt",
		sortOrder: 20,
		fields: [
			{ slug: "user_id", label: "User ID", type: "string", required: true },
			{
				slug: "type",
				label: "Type",
				type: "select",
				validation: { options: ["membership", "course"] },
				required: true,
			},
			{ slug: "item_id", label: "Item ID", type: "string", required: true },
			{ slug: "subtotal", label: "Subtotal", type: "number" },
			{ slug: "discount_amount", label: "Discount", type: "number", defaultValue: 0 },
			{ slug: "amount", label: "Amount", type: "number", required: true },
			{ slug: "currency", label: "Currency", type: "string", defaultValue: "VND" },
			{
				slug: "coupon_id",
				label: "Coupon",
				type: "reference",
				options: { collection: "coupons" },
			},
			{ slug: "coupon_code", label: "Coupon Code", type: "string" },
			{ slug: "payment_provider", label: "Payment Provider", type: "string" },
			{ slug: "payment_id", label: "Payment ID", type: "string" },
			{ slug: "metadata", label: "Metadata", type: "json" },
		],
	},
	{
		slug: "enrollments",
		label: "Enrollments",
		labelSingular: "Enrollment",
		description: "User enrollments in specific courses",
		icon: "book-open-check",
		sortOrder: 20,
		fields: [
			{ slug: "user_id", label: "User ID", type: "string", required: true },
			{
				slug: "course_id",
				label: "Course",
				type: "reference",
				options: { collection: "courses" },
				required: true,
			},
			{
				slug: "source",
				label: "Source",
				type: "select",
				validation: { options: ["membership", "purchase"] },
				required: true,
			},
			{
				slug: "order_id",
				label: "Order",
				type: "reference",
				options: { collection: "orders" },
			},
			{ slug: "progress", label: "Progress %", type: "integer", defaultValue: 0 },
			{ slug: "started_at", label: "Started At", type: "datetime" },
			{ slug: "completed_at", label: "Completed At", type: "datetime" },
		],
	},
	{
		slug: "lesson_progress",
		label: "Lesson Progress",
		labelSingular: "Progress",
		description: "Individual lesson completion and playback state",
		icon: "check-circle",
		sortOrder: 20,
		fields: [
			{ slug: "user_id", label: "User ID", type: "string", required: true },
			{
				slug: "lesson_id",
				label: "Lesson",
				type: "reference",
				options: { collection: "lessons" },
				required: true,
			},
			{
				slug: "course_id",
				label: "Course",
				type: "reference",
				options: { collection: "courses" },
				required: true,
			},
			{ slug: "completed", label: "Completed", type: "boolean", defaultValue: false },
			{ slug: "completed_at", label: "Completed At", type: "datetime" },
			{ slug: "last_position", label: "Last Position (seconds)", type: "integer" },
		],
	},
	{
		slug: "quiz_submissions",
		label: "Quiz Submissions",
		labelSingular: "Submission",
		description: "Student attempts and grading results for quizzes",
		icon: "clipboard-check",
		sortOrder: 20,
		fields: [
			{ slug: "user_id", label: "User ID", type: "string", required: true },
			{
				slug: "quiz_id",
				label: "Quiz",
				type: "reference",
				options: { collection: "quizzes" },
				required: true,
			},
			{
				slug: "lesson_id",
				label: "Lesson",
				type: "reference",
				options: { collection: "lessons" },
			},
			{
				slug: "course_id",
				label: "Course",
				type: "reference",
				options: { collection: "courses" },
			},
			{ slug: "score", label: "Score", type: "number", required: true },
			{ slug: "max_score", label: "Max Score", type: "number", required: true },
			{ slug: "percentage", label: "Percentage", type: "number" },
			{ slug: "passed", label: "Passed", type: "boolean" },
			{ slug: "answers", label: "Answers", type: "json" },
			{ slug: "started_at", label: "Started At", type: "datetime" },
			{ slug: "submitted_at", label: "Submitted At", type: "datetime" },
			{ slug: "time_spent_seconds", label: "Time Spent (seconds)", type: "integer" },
		],
	},
	{
		slug: "certificates",
		label: "Certificates",
		labelSingular: "Certificate",
		description: "Issued course completion certificates",
		icon: "award",
		sortOrder: 20,
		fields: [
			{ slug: "user_id", label: "User ID", type: "string", required: true },
			{
				slug: "course_id",
				label: "Course",
				type: "reference",
				options: { collection: "courses" },
				required: true,
			},
			{
				slug: "template_id",
				label: "Template",
				type: "reference",
				options: { collection: "certificate_templates" },
				required: true,
			},
			{
				slug: "certificate_number",
				label: "Certificate Number",
				type: "string",
				required: true,
				unique: true,
			},
			{ slug: "issued_at", label: "Issued At", type: "datetime" },
			{ slug: "metadata", label: "Metadata", type: "json" },
		],
	},
];
